<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>ed98ac18-2269-40d0-a8bf-a2226a18ad81</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Storage.V1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
  </ItemGroup>

</Project>
